%%metro title: BUSCO pipeline
%%metro style: dark
%%metro line: main | BUSCO| #2db572
%%metro line: qc | Stats aggregation | #0570b0
%%metro file: input| Fasta
%%metro file: report_out | HTML
%%metro files: sequences_tar | Fasta (TAR)
%%metro files: busco_tsv | TSV
%%metro file: busco_summ_json | JSON
%%metro file: busco_summ_txt | TXT

graph LR
    subgraph params_check [Prepare genome]

        input[ ]
        gunzip([Gunzip])
        _no_gunzip
        _uncompressed

        input -->|main,qc| _no_gunzip
        _no_gunzip -->|main,qc| _uncompressed
        input -->|main,qc| gunzip
        gunzip -->|main,qc| _uncompressed
    end

    subgraph busco [BUSCO]
        get_odb([Get ODB lineages])
        busco_busco([BUSCO])

        get_odb -->|main,qc| busco_busco
        busco_busco -->|main| sequences_tar
        busco_busco -->|main| busco_tsv
        busco_busco -->|main| busco_summ_json
        busco_busco -->|main| busco_summ_txt
    end

    subgraph reporting [Reporting]
        multiqc([MultiQC])
        multiqc -->|qc| report_out
    end

    %% Inter-section edges
    _uncompressed -->|main,qc| get_odb
    busco_busco -->|qc| multiqc
